version: '2'
services:
  md2mobi:
    build: .
    labels:
      - "traefik.backend=md2mobi"
      - "traefik.frontend.rule=Host:md2mobi.lapw.at"
      - "traefik.port=8000"
      - "traefik.enable=true"
